[variables]

[[config.domains]]
serviceName = "reef-dev-cluster"
port = 30335
host = "${domain}"
path = "/"

[[config.domains]]
serviceName = "reef-dev-cluster"
port = 30334
host = "${domain}"
path = "/"

[[config.domains]]
serviceName = "reef-dev-cluster"
port = 30333
host = "${domain}"
path = "/"

[[config.domains]]
serviceName = "reef-dev-cluster"
port = 30336
host = "${domain}"
path = "/"

[[config.domains]]
serviceName = "reef-dev-cluster"
port = 9944
host = "${domain}"
path = "/"

[[config.domains]]
serviceName = "reef-dev-cluster"
port = 9945
host = "${domain}"
path = "/"

[[config.domains]]
serviceName = "reef-dev-cluster"
port = 9946
host = "${domain}"
path = "/"

[config.env]
