[variables]
main_domain = "${domain}"

app_openssl_key_v1 = "${password:32}"
app_executor_secret = "${password:32}"

db_root_pass = "${password:32}"
db_user = "appwrite"
db_pass = "${password:32}"
db_schema = "appwrite"

[config]

[[config.domains]]
serviceName = "appwrite"
port = 80
host = "${main_domain}"
path = "/"

[[config.domains]]
serviceName = "appwrite-console"
port = 80
host = "${main_domain}"
path = "/console"

[[config.domains]]
serviceName = "appwrite-realtime"
port = 80
host = "${main_domain}"
path = "/v1/realtime"

[config.env]
_APP_ENV = "production"
_APP_USAGE_STATS = "enabled"

_APP_DOMAIN = "${main_domain}"
_APP_DOMAIN_FUNCTIONS = "${main_domain}"
_APP_DOMAIN_SITES = "${main_domain}"

_APP_OPENSSL_KEY_V1 = "${app_openssl_key_v1}"

_APP_DB_HOST = "mariadb"
_APP_DB_PORT = "3306"
_APP_DB_SCHEMA = "${db_schema}"
_APP_DB_USER = "${db_user}"
_APP_DB_PASS = "${db_pass}"
_APP_DB_ROOT_PASS = "${db_root_pass}"

_APP_REDIS_HOST = "redis"
_APP_REDIS_PORT = "6379"

_APP_EXECUTOR_SECRET = "${app_executor_secret}"
_APP_EXECUTOR_HOST = "openruntimes-executor"

_APP_SMTP_HOST = ""
_APP_SMTP_PORT = ""
_APP_SMTP_SECURE = ""
_APP_SMTP_USERNAME = ""
_APP_SMTP_PASSWORD = ""

_APP_ASSISTANT_OPENAI_API_KEY = ""
