[variables]
main_domain = "${domain}"
db_password = "${password:32}"
app_secret = "${password:64}"

[config]

[[config.domains]]
serviceName = "docmost"
port = 3000
host = "${main_domain}"

[config.env]
MAIN_DOMAIN = "${main_domain}"
DB_PASSWORD = "${db_password}"
APP_SECRET = "${app_secret}"

[[config.mounts]]
