blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Documentation
    url: https://docs.dokploy.com
    about: Check out the official Dokploy documentation for guides and references
  - name: ğŸŒ Website
    url: https://dokploy.com
    about: Visit the official Dokploy website
  - name: ğŸ’¬ GitHub Discussions
    url: https://github.com/Dokploy/dokploy/discussions
    about: Join the community discussions for questions and support
