services:
  cloudflare-warp-proxy:
    image: ghcr.io/seiry/cloudflare-warp-proxy:latest
    restart: unless-stopped
    environment:
      - LICENSE=${WARP_KEY}
    logging:
      driver: json-file
      options:
        max-size: 1m
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
