services:
  cloudflare-warp-proxy:
    image: ghcr.io/seiry/cloudflare-warp-proxy:latest
    restart: unless-stopped
    environment:
      - LICENSE=${WARP_KEY}
    logging:
      driver: json-file
      options:
        max-size: 1m
