[variables]
cloudflare_warp_token = "<Get from Cloudflare Zero Trust Dashboard>"

[config]
domains = []

[config.env]
LICENSE = "${cloudflare_warp_token}"

[[config.mounts]]
filePath = "/run/dbus/system_bus_socket"
content = ""