services:
  nodelink:
    image: performanc/nodelink:latest
    volumes:
      - ../files/config.js:/app/config.js
    expose:
      - "3000"
    restart: unless-stopped
    environment:
      NODELINK_SERVER_PASSWORD: "${NODELINK_SERVER_PASSWORD:-youshallnotpass}"
      NODELINK_SERVER_PORT: "${NODELINK_SERVER_PORT:-3000}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2333/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s