[variables]
main_domain = "${domain}"
db_password = "${password:32}"

[config]
[[config.domains]]
serviceName = "easyappointments"
port = 80
host = "${main_domain}"

[[config.env]]
value = "DOMAIN=${main_domain}"

[[config.env]]
value = "DB_PASSWORD=${db_password}"
