version: "3.8"

services:
  docling-serve:
    image: ghcr.io/ds4sd/docling-serve:v0.5.1
    restart: unless-stopped
    environment:
      DOCLING_SERVE_ENABLE_UI: ${DOCLING_SERVE_ENABLE_UI}
      DOCLING_SERVE_HOST: ${DOCLING_SERVE_HOST}
      DOCLING_SERVE_PORT: ${DOCLING_SERVE_PORT}
    volumes:
      - docling-data:/opt/app-root/src/.cache/docling/models

volumes:
  docling-data:

