[variables]
main_domain = "${domain}"
db_password = "${password:32}"
minio_password = "${password:32}"
rabbitmq_user = "${username}"
rabbitmq_pass = "${password:32}"
secret_key = "${base64:48}"
live_server_secret_key = "${base64:32}"

[config]
env = [
  "APP_DOMAIN=${main_domain}",
  "APP_RELEASE=v1.2.1",
  "WEB_URL=https://${main_domain}",
  "PGHOST=plane-db",
  "PGDATABASE=plane",
  "POSTGRES_USER=plane",
  "POSTGRES_PASSWORD=${db_password}",
  "POSTGRES_DB=plane",
  "POSTGRES_PORT=5432",
  "PGDATA=/var/lib/postgresql/data",
  "REDIS_HOST=plane-redis",
  "REDIS_PORT=6379",
  "REDIS_URL=redis://plane-redis:6379/",
  "MINIO_ROOT_USER=access-key",
  "MINIO_ROOT_PASSWORD=${minio_password}",
  "AWS_REGION=",
  "AWS_ACCESS_KEY_ID=access-key",
  "AWS_SECRET_ACCESS_KEY=${minio_password}",
  "AWS_S3_ENDPOINT_URL=http://plane-minio:9000",
  "AWS_S3_BUCKET_NAME=uploads",
  "BUCKET_NAME=uploads",
  "FILE_SIZE_LIMIT=5242880",
  "RABBITMQ_HOST=plane-mq",
  "RABBITMQ_PORT=5672",
  "RABBITMQ_USER=${rabbitmq_user}",
  "RABBITMQ_PASSWORD=${rabbitmq_pass}",
  "RABBITMQ_DEFAULT_USER=${rabbitmq_user}",
  "RABBITMQ_DEFAULT_PASS=${rabbitmq_pass}",
  "RABBITMQ_DEFAULT_VHOST=plane",
  "RABBITMQ_VHOST=plane",
  "API_BASE_URL=http://api:8000",
  "DEBUG=0",
  "CORS_ALLOWED_ORIGINS=https://${main_domain}",
  "GUNICORN_WORKERS=1",
  "USE_MINIO=1",
  "DATABASE_URL=postgresql://plane:${db_password}@plane-db/plane",
  "SECRET_KEY=${secret_key}",
  "LIVE_SERVER_SECRET_KEY=${live_server_secret_key}",
  "AMQP_URL=amqp://${rabbitmq_user}:${rabbitmq_pass}@plane-mq:5672/plane",
  "API_KEY_RATE_LIMIT=60/minute",
  "MINIO_ENDPOINT_SSL=0",
  "SITE_ADDRESS=:80",
  "LISTEN_HTTP_PORT=80",
  "LISTEN_HTTPS_PORT=443"
]
mounts = []

[[config.domains]]
serviceName = "proxy"
port = 80
host = "${main_domain}"
