[variables]
BETTER_AUTH_SECRET = "${password:64}"
BETTER_AUTH_URL = "http://localhost:3000"
DATABASE_URL = "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
POSTGRES_DB = "dokistry"
POSTGRES_USER = "${username}"
POSTGRES_PASSWORD = "${password:64}"

[config]
[[config.domains]]
serviceName = "dokistry"
port = 3000
host = "${domain}"

[config.env]
BETTER_AUTH_SECRET = "${BETTER_AUTH_SECRET}"
BETTER_AUTH_URL = "${BETTER_AUTH_URL}"
DATABASE_URL = "${DATABASE_URL}"
POSTGRES_DB = "${POSTGRES_DB}"
POSTGRES_USER = "${POSTGRES_USER}"
POSTGRES_PASSWORD = "${POSTGRES_PASSWORD}"