[config.env]
LOGGING_DRIVER="local"
LOGGING_MAX_SIZE="20m"
LOGGING_MAX_FILES="5"
LOGGING_COMPRESS="true"

TRIGGER_IMAGE_TAG="v4-beta"
RESTART_POLICY="unless-stopped"

TRIGGER_WORKER_TOKEN=""
MANAGED_WORKER_SECRET=""
TRIGGER_API_URL="http://example.com:3000"
OTEL_EXPORTER_OTLP_ENDPOINT="http://example.com:3000/otel"
DOCKER_REGISTRY_URL="registry.com:5000"
DOCKER_REGISTRY_USERNAME=""
DOCKER_REGISTRY_PASSWORD=""

DOCKER_PROXY_IMAGE_TAG="latest"
