version: "3.8"

services:
  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    volumes:
      - rustfs-data:/data
    environment:
      - RUSTFS_ACCESS_KEY
      - RUSTFS_SECRET_KEY
      - RUSTFS_ADDRESS
      - RUSTFS_CONSOLE_ADDRESS
      - RUSTFS_EXTERNAL_URL
      - RUSTFS_CONSOLE_EXTERNAL_URL
      - RUSTFS_CONSOLE_ENABLE
      - RUSTFS_CORS_ALLOWED_ORIGINS
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS
      - RUSTFS_REGION
      - RUSTFS_LOG_LEVEL
    command: /data

volumes:
  rustfs-data: {}
