[variables]
PORT = "8545"
NODE_RPC_URL = "ws://reef.host:9944"

[[config.domains]]
serviceName = "reef-eth-rpc"
port = 8545
host = "${domain}"
path = "/"

[config.env]
PORT = "8545"
NODE_RPC_URL = "ws://reef.host:9944"